version: "2"
run:
  tests: true
  go: "1.26"
linters:
  enable:
    - copyloopvar
    - decorder
    - dupl
    - funcorder
    - gocritic
    - gocyclo
    - godot
    - gosec
    - lll
    - misspell
    - predeclared
    - staticcheck
    - unparam
    - whitespace
  settings:
    gocyclo:
      min-complexity: 15
    godot:
      scope: all
      period: false
    # revive:
    #   rules:
    #     - name: dot-imports
    #     - name: exported
    #     - name: var-naming
    #     - name: receiver-naming
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      # - std-error-handling
    paths:
      - ^tools/docgen/.*\.go$
      - ^internal/command/si\.go$
      - ^internal.command/si/*
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/tfquery/tfquery
  exclusions:
    generated: lax
    paths:
      - ^tools/docgen/.*\.go$
      - ^internal/command/si\.go$
      - ^internal.command/si/*
      - third_party$
      - builtin$
      - examples$
