# Copyright (c) 2026 Steve Taranto staranto@gmail.com.
# SPDX-License-Identifier: Apache-2.0

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: tfquery
    binary: tfquery
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - linux
      - windows
    flags:
      - -trimpath
    ldflags:
      - '-s -w -extldflags "-static"'
      - '-X "github.com/tfquery/tfquery/internal/version.Version={{ .Version }}"'

archives:
  - id: archive
    formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else if eq .Arch "386" }}i386{{- else }}{{ .Arch }}{{- end }}{{- if .Arm }}v{{ .Arm }}{{ end }}'
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE*
      - README.md
      - docs/man/**/*
      - docs/tldr/*

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: tfquery
    name: tfquery
  draft: true
  mode: replace
  footer: >-

    Copyright (c) 2026 Steve Taranto staranto@gmail.com.

    <hr />

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

brews:
  - name: tfquery
    ids: [archive]
    repository:
      owner: tfquery
      name: homebrew-tfquery
    homepage: https://github.com/tfquery/tfquery
    description: CLI to query Terraform/OpenTofu state across backends
    license: Apache-2.0
    url_template: "https://github.com/tfquery/homebrew-tfquery/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    install: |
      bin.install "tfquery"
      man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
    test: |
      system "#{bin}/tfquery", "--version"

nfpms:
  - id: tfquery-deb
    ids: [tfquery]
    package_name: tfquery
    file_name_template: '{{ .Binary }}_{{ .Version }}_{{- if eq .Arch "amd64" }}amd64{{ else }}{{ .Arch }}{{ end }}{{ .ConventionalExtension }}'
    vendor: Steve Taranto
    maintainer: Steve Taranto staranto@gmail.com
    homepage: https://github.com/tfquery/tfquery
    description: CLI for Terraform query
    license: Apache-2.0
    bindir: /usr/local/bin
    formats:
      - deb
    contents:
      - src: docs/man/share/man1/*
        dst: /usr/share/man/man1/
      - src: LICENSE*
        dst: /usr/share/doc/tfquery/
      - src: README.md
        dst: /usr/share/doc/tfquery/
      - src: docs/tldr/*
        dst: /usr/share/doc/tfquery/tldr/

signs:
  - artifacts: all
    cmd: gpg
    output: true
    stdin: "{{ .Env.GPG_PASSPHRASE }}"
    args:
      - "--batch"
      - "--yes"
      - "--pinentry-mode"
      - "loopback"
      - "--passphrase-fd"
      - "0"
      - "--detach-sign"
      - "--armor"
      - "--output"
      - "${signature}"
      - "${artifact}"
