.TH tfctl 1 "June 17, 2026" "tfctl v2.0.0" "tfctl"
.SH NAME
tfctl \- Terraform Control
.SH USAGE
tfq [global options] [command [command options]]
.SH COMMANDS

.TP
\fBmq | module\fR
module registry query

.TP
\fBoq | org\fR
organization query

.TP
\fBpq | project\fR
project query

.TP
\fBps | summarize\fR
plan summary

.TP
\fBrq | run\fR
run query

.TP
\fBsq | state\fR
state query

.TP
\fBsvq | state-version\fR
state version query

.TP
\fBwq | workspace\fR
workspace query

.SH GLOBAL OPTIONS

.TP
\fB--help,\fR
show tfq command help


.TP
\fB--version, -v\fR
tfq version info

