.TH tfquery-sq 1 "June 24, 2026" "tfquery v2.0.0" "tfquery"
.SH NAME
tfquery\-sq \- State Query
.SH SYNOPSIS
tfquery sq [RootDir...] [options]
.br
tfquery state [RootDir...] [options]
.SH DESCRIPTION
Query Terraform state files.

.SH OPTIONS

.TP
\fB--attrs/-a string\fR
Comma-separated list of attributes to include in results.

.fi
There are many possible attributes depending on the command. Common attributes include: `id`, `type`, `name`, `created-at`, `updated-at`, etc. But, each command has it's own schema. Other than the `sq` command, use the `--schema` flag to see the full list of available attributes.

There is also a feature-rich syntax for transforming attribute values. See [Attributes](../attrs.md) for details.
.nf


.TP
\fB--chop/--no-chop\fR
Chop common resource prefix from names.


.TP
\fB--color/--no-color\fR
Colorize text output.


.TP
\fB--concrete/-k\fR
Only include concrete resources.


.TP
\fB--diff [ old[:new] \| + ]\fR
Find differences between state versions.

.fi
The `old` and `new` parameters can be version numbers, `latest`, or `earliest`. If `+` is provided, compares the latest version to the previous version.
.nf


.TP
\fB--filter/-f string\fR
Comma-separated list of filters to apply to results


.TP
\fB--host/-h string\fR
HCP/TFE host to use. Overrides the backend.


.TP
\fB--jq string\fR
jq query string to apply to results.


.TP
\fB--json-into string\fR
secondary output path to write JSON output to.


.TP
\fB--local/--no-local\fR
Show timestamps in local time according to your OS.


.TP
\fB--org string\fR
Organization to use for all commands. Overrides the backend.


.TP
\fB--output/-o string\fR
Output format (text (default), json, yaml, csv).

.fi
The `text` output format is a human-friendly table format. The `json`, `yaml`, and `csv` formats are machine-friendly and can be used for further processing.
.nf


.TP
\fB--padding int\fR
Number of spaces to pad columns in text output.


.TP
\fB--passphrase string\fR
OpenTofu encrypted state passphrase.


.TP
\fB--short/--no-short\fR
Shorten full resource name paths.


.TP
\fB--sort/-s string\fR
Comma-separated list of fields to sort by.

.fi
Prefix field names with `-` to sort in descending order.  For example, `--sort=-created-at,name` sorts first by Created At (newest first), then by Name (A-Z).
.nf


.TP
\fB--sv string\fR
State version to query.  Can be a version number, `latest`, or `earliest`.

.fi
Can also be relativative. For example, `-1` is the previous version, `-2` is two versions ago, `+1` is the next version, and so on.
.nf


.TP
\fB--titles/--no-titles\fR
Include column headings in text output.


.TP
\fB--tldr\fR
Show tldr page if a client is installed.


.TP
\fB--workspace/-w string\fR
Workspace to use for all commands. Overrides the backend.


.TP
\fB--yaml-into string\fR
secondary output path to write YAML output to.




.SH EXAMPLES

.TP
Display state file in current directory and include Created At information.
.IP
tfquery sq --attrs created-at

.TP
Aggregates the state files in the `iac1/` and `iac2/` directories and displays combined results.
.IP
tfquery sq iac1/ iac2/

.TP
Display only concrete resources with "vpc" in their type or name.
.IP
tfquery sq --concrete --filter 'resource@vpc'

.TP
Display the third most recent state file version in JSON format.
.IP
tfquery sq --sv -3 --output json



.SH NOTES

.IP
`sq` operates against one or more IaC root directories.  When multiple [RootDir] values are provided, results are aggregated.  Defaults to CWD when not provided.

.IP
When using encrypted state, `sq` will prompt for a passphrase or use `TF_VAR_passphrase`.

