.TH tfquery-ps 1 "July 6, 2026" "tfquery v1.7.0" "tfquery"
.SH NAME
tfquery\-ps \- Plan summary
.SH SYNOPSIS
tfquery ps [planfile] [options]
.br
tfquery summarize [planfile] [options]
.SH DESCRIPTION
Show a summary of the given plan.

.SH OPTIONS

.TP
\fB--color/--no-color\fR
Colorize text output.


.TP
\fB--filter/-f string\fR
Comma-separated list of filters to apply to results


.TP
\fB--jq string\fR
jq query string to apply to results.


.TP
\fB--json-into string\fR
secondary output path to write JSON output to.


.TP
\fB--local/--no-local\fR
Show timestamps in local time according to your OS.


.TP
\fB--output/-o string\fR
Output format (text (default), json, yaml, csv).

.fi
The `text` output format is a human-friendly table format. The `json`, `yaml`, and `csv` formats are machine-friendly and can be used for further processing.
.nf


.TP
\fB--padding int\fR
Number of spaces to pad columns in text output.


.TP
\fB--sort/-s string\fR
Comma-separated list of fields to sort by.

.fi
Prefix field names with `-` to sort in descending order. For example, `--sort=-created-at,name` sorts first by Created At (newest first), then by Name (A-Z).
.nf


.TP
\fB--titles/--no-titles\fR
Include column headings in text output.


.TP
\fB--tldr\fR
Show tldr page if a client is installed.


.TP
\fB--yaml-into string\fR
secondary output path to write YAML output to.




.SH EXAMPLES

.TP
Show only a summary of a Terraform plan.
.IP
terraform plan | tfquery ps

.TP
Show the full plan output while also including a summary.
.IP
terraform plan | tee >(tfquery ps)


