.TH tfquery-svq 1 "August 15, 2026" "tfquery v1.8.0" "tfquery"
.SH NAME
tfquery\-svq \- State Version Query
.SH SYNOPSIS
tfquery svq [RootDir] [options]
.br
tfquery state-version [RootDir] [options]
.SH DESCRIPTION
Query Terraform state version history.

.SH OPTIONS

.TP
\fB--attrs/-a string\fR
Comma-separated list of attributes to include in results.

.fi
There are many possible attributes depending on the command. Common attributes include: `id`, `type`, `name`, `created-at`, `updated-at`, etc. But, each command has it's own schema. Other than the `sq` command, use the `--schema` flag to see the full list of available attributes.

There is also a feature-rich syntax for transforming attribute values. See [Attributes](../attrs.md) for details.
.nf


.TP
\fB--color/--no-color\fR
Colorize text output.


.TP
\fB--filter/-f string\fR
Comma-separated list of filters to apply to results


.TP
\fB--host/-h string\fR
HCP/TFE host to use. Overrides the backend.


.TP
\fB--jq string\fR
jq query string to apply to results.


.TP
\fB--json-into string\fR
secondary output path to write JSON output to.


.TP
\fB--limit int\fR
Limit the result set to `int` results.


.TP
\fB--local/--no-local\fR
Show timestamps in local time according to your OS.


.TP
\fB--org string\fR
Organization to use for all commands. Overrides the backend.


.TP
\fB--output/-o string\fR
Output format (text (default), json, yaml, csv).

.fi
The `text` output format is a human-friendly table format. The `json`, `yaml`, and `csv` formats are machine-friendly and can be used for further processing.
.nf


.TP
\fB--padding int\fR
Number of spaces to pad columns in text output.


.TP
\fB--sort/-s string\fR
Comma-separated list of fields to sort by.

.fi
Prefix field names with `-` to sort in descending order. For example, `--sort=-created-at,name` sorts first by Created At (newest first), then by Name (A-Z).
.nf


.TP
\fB--titles/--no-titles\fR
Include column headings in text output.


.TP
\fB--tldr\fR
Show tldr page if a client is installed.


.TP
\fB--workspace/-w string\fR
Workspace to use for all commands. Overrides the backend.


.TP
\fB--yaml-into string\fR
secondary output path to write YAML output to.




.SH EXAMPLES

.TP
Display state file history for current directory and include Created At information.
.IP
tfquery svq --attrs created-at

.TP
Display the five most recent state file versions and include the YYYY-MM-DD portion of the Created At information.
.IP
tfquery svq --limit 5 --attrs created-at::10


