.TH tfquery 1 "August 16, 2026" "tfquery v1.8.0" "tfquery"
.SH NAME
tfquery \- Terraform Control
.SH USAGE
tfquery [global options] [command [command options]]
.SH COMMANDS

.TP
\fBmq | module\fR
module registry query

.TP
\fBoq | org\fR
organization query

.TP
\fBpq | project\fR
project query

.TP
\fBps | summarize\fR
plan summary

.TP
\fBrq | run\fR
run query

.TP
\fBsq | state\fR
state query

.TP
\fBsvq | state-version\fR
state version query

.TP
\fBwq | workspace\fR
workspace query

.SH GLOBAL OPTIONS

.TP
\fB--help,\fR
show tfquery command help


.TP
\fB--version, -v\fR
tfquery version info

